vm_rule_set: vm_default
label_rule_set: label_default
attribute_rule_sets:
- name: port_group
  attribute: SSH_PORT
  prefix: port_
  value_rules: []
sanitization_rules:
  vm_default:
    prefix: vm_
    name_rules:
    - pattern: ^([a-zA-Z]+)\..*
      replacement: $1
    - pattern: '[-0-9].*'
      replacement: ''
    - pattern: '-'
      replacement: _
  label_default:
    prefix: label_
    name_rules:
    - pattern: '[\-\.]'
      replacement: _
servers:
- endpoint: http://one.snapp.tech
  port: 2633
  user: onemonitoring
  password: "password"
- endpoint: http://new-one.snapp.tech
  port: 2633
  user: one.monitoring
  password: "password"