namespace: sysops
name: opennebula_inventory
version: 1.0.0
readme: README.md
authors:
  - Hamed Maleki hamed.maaleki@gmail.com
description: An Ansible inventory plugin for OpenNebula, supporting dynamic grouping by VM names, labels, and attributes.
license:
  - GPL-3.0-or-later
dependencies: {}
repository: https://github.com/your_username/opennebula_inventory
documentation: https://github.com/your_username/opennebula_inventory/blob/main/docs/opennebula_inventory.md
homepage: https://github.com/your_username/opennebula_inventory
issues: https://github.com/your_username/opennebula_inventory/issues
build_ignore:
  - .gitignore
