namespace: haameed
name: opennebula_dynamic_inventory
version: "1.0.0"
readme: README.md
authors:
  - Hamed Maleki <hamed.maaleki@gmail.com>
description: An Ansible inventory plugin for OpenNebula, supporting dynamic grouping by VM names, labels, and attributes.
tags:
  - inventory
  - opennebula
  - dynamic
  - cloud
license:
  - GPL-3.0-or-later
dependencies: {}
repository: https://github.com:Haameed/opennebula-dynamic-inventory
documentation: https://github.com/Haameed/opennebula-dynamic-inventory/blob/main/docs/opennebula_inventory.md
homepage: https://github.com:Haameed/opennebula-dynamic-inventory
issues: https://github.com:Haameed/opennebula-dynamic-inventory/issues
build_ignore:
  - .gitignore